services:
  registry:
    image: registry:2
    container_name: docker-registry
    restart: always
    networks:
      - proxy
    volumes:
      - ./data:/var/lib/registry
      - ./auth:/auth
      - ./config.yml:/etc/docker/registry/config.yml
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.registry-api.rule=Host(`stage-registry.nearbee.ir`)"
      - "traefik.http.routers.registry-api.entrypoints=websecure"
      - "traefik.http.routers.registry-api.tls.certresolver=myresolver"
      - "traefik.http.services.registry-api.loadbalancer.server.port=5000"
      - "traefik.http.middlewares.registry-auth.basicauth.usersfile=/auth/htpasswd"
      - "traefik.http.routers.registry-api.middlewares=registry-auth"

networks:
  proxy:
    external: true