services:
  registry:
    image: registry:2
    container_name: docker-registry
    restart: always
    networks:
      - proxy
    volumes:
      - ./data:/var/lib/registry
      - ./auth:/auth
      - ./config.yml:/etc/docker/registry/config.yml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.registry-api.rule=Host(`stage-registry.nearbee.ir`)"
      - "traefik.http.routers.registry-api.entrypoints=websecure"
      - "traefik.http.routers.registry-api.tls.certresolver=myresolver"
      - "traefik.http.services.registry-api.loadbalancer.server.port=5000"

  registry-ui:
    image: joxit/docker-registry-ui:latest
    container_name: registry-ui
    restart: always
    networks:
      - proxy
    environment:
      REGISTRY_TITLE: My Docker Registry
      REGISTRY_URL: http://registry:5000
      DELETE_IMAGES: "true"
      SINGLE_REGISTRY: "true"
    depends_on:
      - registry
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.registry-ui.rule=Host(`stage-registry-ui.nearbee.ir`)"
      - "traefik.http.routers.registry-ui.entrypoints=websecure"
      - "traefik.http.routers.registry-ui.tls.certresolver=myresolver"
      - "traefik.http.services.registry-ui.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
