version: "3.5"
services:
  elasticsearch:
    container_name: temporal-elasticsearch
    environment:
      - cluster.routing.allocation.disk.threshold_enabled=true
      - cluster.routing.allocation.disk.watermark.low=512mb
      - cluster.routing.allocation.disk.watermark.high=256mb
      - cluster.routing.allocation.disk.watermark.flood_stage=128mb
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - xpack.security.enabled=false
    image: elasticsearch:${ELASTICSEARCH_VERSION}
    networks:
      - temporal-network
      - db-back
    expose:
      - 9200
    volumes:
      - /var/lib/elasticsearch/data
  temporal:
    container_name: temporal
    depends_on:
      - elasticsearch
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=nimamleo
      - POSTGRES_PWD=root
      - POSTGRES_SEEDS=pgsql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
      - ENABLE_ES=true
      - ES_SEEDS=elasticsearch
      - ES_VERSION=v7
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/auto-setup:${TEMPORAL_VERSION}
    networks:
      - temporal-network
      - db-back
      - proxy
    ports:
      - 7233:7233
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.temporal.rule=Host(`testing-temporal.elsa-gallery.shop`) && PathPrefix(`/api`)"
      - "traefik.http.routers.temporal.entrypoints=websecure"
      - "traefik.http.routers.temporal.tls.certresolver=myresolver"
      - "traefik.http.services.temporal.loadbalancer.server.port=7233"
  temporal-admin-tools:
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:${TEMPORAL_ADMINTOOLS_VERSION}
    networks:
      - temporal-network
    stdin_open: true
    tty: true
  temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=https://testing-temporal.elsa-gallery.shop
    image: temporalio/ui:${TEMPORAL_UI_VERSION}
    networks:
      - temporal-network
      - proxy
    ports:
      - 8080:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.temporal-ui.rule=Host(`testing-temporal.elsa-gallery.shop`)"
      - "traefik.http.routers.temporal-ui.entrypoints=websecure"
      - "traefik.http.routers.temporal-ui.tls.certresolver=myresolver"
      - "traefik.http.services.temporal-ui.loadbalancer.server.port=8080"
networks:
  temporal-network:
    driver: bridge
    name: temporal-network
  db-back:
    external: true
  proxy:
    external: true
