services:
  pg18:
    image: postgis/postgis:18-3.6
    container_name: pg18
    env_file: ./.env
    volumes:
      - ./pg18_data:/var/lib/postgresql
    networks: [app]

networks:
  app:
    external: true

