services:
  pg18:
    image: postgis/postgis:18-3.6
    container_name: pg18
    restart: always
    env_file: ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./pg18_data:/var/lib/postgresql
    networks: [app]

networks:
  app:
    external: true
