
services:
  elasticsearch:
    image: elasticsearch:7.17.27
    container_name: elasticsearch
    env_file:
      - .env
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - elasticsearch_network
    restart: unless-stopped

  kibana:
    image: kibana:7.17.0
    container_name: kibana
    env_file:
      - .env
    depends_on:
      - elasticsearch
    networks:
      - elasticsearch_network
    restart: unless-stopped

  logstash:
    image: logstash:7.17.0
    container_name: logstash
    env_file:
      - .env
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    depends_on:
      - elasticsearch
    networks:
      - elasticsearch_network
    restart: unless-stopped

volumes:
  elasticsearch_data:
    driver: local

networks:
  elasticsearch_network:
    external: true
