
services:
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    env_file:
      - ./.env
    volumes:
      - minio_data:/data
    networks:
      - app
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.minio.rule=Host(`stage-storage.nearbee.ir`)"
      - "traefik.http.routers.minio.entrypoints=websecure"
      - "traefik.http.routers.minio.tls.certresolver=myresolver"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"

volumes:
  minio_data:

networks:
  app:
    external: true
  proxy:
    external: true
