version: "3.9"

services:
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    env_file:
      - ./.env
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"   
      - "9001:9001" 
    networks:
      - app

volumes:
  minio_data:

networks:
  app:
    external: true

