services:
  chroma:
    image: chromadb/chroma
    container_name: chromadb
    restart: unless-stopped
    volumes:
      - ./chroma-data:/data  
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_PORT=8000
    networks:
      - chroma

volumes:
  chroma-data:
    driver: local

networks:
  chroma:
    external: true
