services:
  redis:
    image: redis:7.2.6-alpine
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    

volumes:
  redis_data:
    name: redis_data


